import { Observable } from 'rxjs';
import { ObservableSpy, ObserverSpyConfig } from './observableSpy';
import { SubscribedSpy } from './SubscribedSpy';

/**
 * Verification step signature that is used to verify received values from the tested observable.
 * Verification steps are used to create reusable assertions for observables.
 *
 * @typeParam T - Type of values that are generated by the observable.
 */
export interface VerificationStep<T> {
	/**
	 * Function is invoked on the next event received from the observable.
	 *
	 * @param val - Received value on the next event.
	 * @param index - Index of the received next value.
	 * @param observableSpy - Spy that is subscribed to the tested observable.
	 *
	 * @returns True if this step is completed and should proceed the check of the next verification step, otherwise false.
	 */
	next(val: T, index: number, observableSpy: SubscribedSpy<T>): boolean;

	/**
	 * Function is invoked on the error event received from the observable.
	 *
	 * @param error - Received error on the error event.
	 * @param observableSpy - Spy that is subscribed to the tested observable.
	 *
	 * @returns True if this step is completed and should proceed the check of the next verification step, otherwise false.
	 */
	error(e: unknown, observableSpy: SubscribedSpy<T>): boolean;

	/**
	 * Function is invoked on the complete event received from the observable.
	 *
	 * @param observableSpy - Spy that is subscribed to the tested observable.
	 *
	 * @returns True if this step is completed and should proceed the check of the next step, otherwise false.
	 */
	complete(observableSpy: SubscribedSpy<T>): boolean;
}

/**
 * Helper function that is used to verify if observables behave as expected.
 *
 * @typeParam T - Type of values that are generated by the observable.
 *
 * @param observable - Observable that is tested.
 * @param steps - Verification  steps that will be used to verify behavior of the tested observable.
 * @param config - Spy configuration.
 *
 * @returns Promise with received values from observable if it's complete successfully, otherwise it returns an error.
 */
export function verifyObservable<T>(
	observable: Observable<T>,
	steps: VerificationStep<T>[],
	config?: ObserverSpyConfig,
): Promise<T[]> {
	return new Promise((resolve, reject) => {
		const observableSpy = new ObservableSpy(observable, config);
		observableSpy.addNextListener((value, index, o) => {
			try {
				const { next } = steps[0];
				const isDone = next(value, index, o);
				isDone && steps.splice(0, 1);
			} catch (e) {
				o.unsubscribe();
				reject(e);
			}
		});

		observableSpy.addErrorListener((e, o) => {
			try {
				const { error } = steps[0];
				const isDone = error(e, o);
				isDone && steps.splice(0, 1);
				resolve(o.getValues());
			} catch (assertError) {
				o.unsubscribe();
				reject(assertError);
			}
		});

		observableSpy.addCompleteListener((o) => {
			try {
				const { complete } = steps[0];
				const isDone = complete(o);
				isDone && steps.splice(0, 1);
				resolve(o.getValues());
			} catch (e) {
				o.unsubscribe();
				reject(e);
			}
		});

		observableSpy.subscribe();
	});
}
