import { Observable } from 'rxjs';
import { ObservableSpy, ObserverSpyConfig } from './observableSpy';
import { SubscribedSpy } from './SubscribedSpy';

/**
 * Helper function that will create an observable spy and subscribe a spy to the tested observable.
 *
 * @typeParam T - Type of values that are generated by the observable.
 *
 * @param observable - Rxjs observable that will be tested by spy.
 * @param config - Spy configuration.
 */
export function subscribeSpyTo<T>(
	observable: Observable<T>,
	config?: ObserverSpyConfig,
): SubscribedSpy<T> {
	const observableSpy = new ObservableSpy(observable, config);
	observableSpy.subscribe();

	return observableSpy;
}

