import { ObservableSpyAssertionError } from '../../../errors';
import { expectedSignalActualError } from '../../../messages';
import { EventType } from '../../../spy';
import { VerificationStep } from '../../verifyObservable';

/**
 * Creates awaitComplete verification step that ignores all next values received from the observable.
 * Check if the observable will end with a complete event.
 *
 * @typeParam T - Type of value that is generated by the observable.
 *
 * @param stepName - Name of the verification step.
 * @param expectedCallback - Optional callback that will receive next values.
 * @param observableName - Optional name of the observable.
 *
 * @returns Created verification step.
 */
export default function createAwaitCompleteStep<T>(
	stepName: string,
	expectedCallback?: null | ((value: T, index: number) => void),
	observableName?: string,
): VerificationStep<T> {
	return {
		next: (val, index) => {
			expectedCallback && expectedCallback(val, index);
			return false;
		},
		error: (error) => {
			const errorMessage = expectedSignalActualError(
				stepName,
				EventType.Complete,
				EventType.Error,
				error,
				observableName,
			);
			throw new ObservableSpyAssertionError(errorMessage, {
				error,
				expectedEvent: EventType.Complete,
				receivedEvent: EventType.Error,
			});
		},
	};
}

