name: development

on:
  pull_request:
    branches:
      - master

jobs:
  development_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Link project packages
        run: npm run bootstrap

      - name: Build packages
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run ESlint code quality checks
        run: npm run lint

