name: observable-spy-release

on:
  push:
    branches:
      - master
    paths:
      - 'packages/observableSpy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run bootstrap
      - run: npm test
      - run: cd ./packages/observableSpy
      - run: rm -rf dist/test
      - run: mv -v dist/src/* dist/
      - run: rm -rf dist/src

