name: observable-spy-release

on:
  push:
    branches:
      - master
    paths:
      - 'packages/observableSpy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run bootstrap
      - run: npm run build
      - run: npm test
      - run: rm -rf packages/observableSpy/dist/test
      - run: mv -v packages/observableSpy/dist/src/* packages/observableSpy/dist/
      - run: rm -rf packages/observableSpy/dist/src

